create schema if not exists private;

create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Home',
  address text not null,
  province text not null,
  city text not null,
  street text not null,
  postal_code text not null,
  created_at timestamptz not null default now(),
  constraint addresses_lengths_check check (
    char_length(label) between 1 and 80
    and char_length(address) between 1 and 200
    and char_length(province) between 1 and 100
    and char_length(city) between 1 and 100
    and char_length(street) between 1 and 200
    and char_length(postal_code) between 1 and 20
  )
);

create index if not exists addresses_user_created_idx
  on public.addresses (user_id, created_at desc);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  constraint contact_messages_status_check
    check (status in ('new', 'in_progress', 'resolved', 'spam')),
  constraint contact_messages_lengths_check check (
    char_length(name) between 1 and 160
    and char_length(email) between 3 and 320
    and char_length(message) between 1 and 3000
  )
);

create index if not exists contact_messages_status_created_idx
  on public.contact_messages (status, created_at desc);

create table if not exists private.api_rate_limits (
  rate_key text primary key,
  window_started timestamptz not null,
  request_count integer not null,
  constraint api_rate_limits_count_check check (request_count > 0)
);

alter table public.addresses enable row level security;
alter table public.contact_messages enable row level security;
alter table private.api_rate_limits enable row level security;

revoke all on table public.addresses, public.contact_messages
  from public, anon, authenticated;
revoke all on table private.api_rate_limits
  from public, anon, authenticated, service_role;

grant select, insert, update, delete on table public.addresses to service_role;
grant select, insert, update, delete on table public.contact_messages to service_role;
grant usage, select on sequence public.addresses_id_seq to service_role;
grant usage, select on sequence public.contact_messages_id_seq to service_role;
grant select, insert, update on table public.profiles to service_role;

-- Ownership RLS alone does not prevent a user from updating privileged columns
-- in their own row. Keep self-service updates limited to non-authority fields.
revoke update on table public.profiles from authenticated;
grant update (first_name, last_name, phone) on table public.profiles to authenticated;

do $block$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_public_fields_length_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_public_fields_length_check check (
        (first_name is null or char_length(first_name) <= 120)
        and (last_name is null or char_length(last_name) <= 120)
        and (phone is null or char_length(phone) <= 50)
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'vendor_requests_core_fields_length_check'
      and conrelid = 'public.vendor_requests'::regclass
  ) then
    alter table public.vendor_requests
      add constraint vendor_requests_core_fields_length_check check (
        char_length(email) between 3 and 320
        and char_length(business_name) between 1 and 160
        and char_length(phone) between 1 and 50
      ) not valid;
  end if;
end;
$block$;

create or replace function public.consume_api_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  current_count integer;
begin
  if p_key is null
     or char_length(p_key) <> 64
     or p_limit < 1
     or p_limit > 1000
     or p_window_seconds < 1
     or p_window_seconds > 86400 then
    raise exception 'Invalid rate-limit configuration';
  end if;

  insert into private.api_rate_limits as limits (
    rate_key,
    window_started,
    request_count
  )
  values (p_key, clock_timestamp(), 1)
  on conflict (rate_key) do update
  set window_started = case
        when limits.window_started <= clock_timestamp() - make_interval(secs => p_window_seconds)
          then clock_timestamp()
        else limits.window_started
      end,
      request_count = case
        when limits.window_started <= clock_timestamp() - make_interval(secs => p_window_seconds)
          then 1
        else limits.request_count + 1
      end
  returning request_count into current_count;

  if current_count > p_limit then
    raise sqlstate 'PGRST'
      using message = json_build_object(
        'code', 'rate_limited',
        'message', 'Too many requests. Please try again later.'
      )::text,
      detail = json_build_object(
        'status', 429,
        'headers', json_build_object('Retry-After', p_window_seconds)
      )::text;
  end if;
end;
$function$;

revoke execute on function public.consume_api_rate_limit(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_api_rate_limit(text, integer, integer)
  to service_role;

-- Trigger and event-trigger functions must never be exposed as callable RPCs.
revoke execute on function public.handle_new_user()
  from public, anon, authenticated;
do $block$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke execute on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end;
$block$;

-- New API objects are private by default; migrations must grant access explicitly.
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated;
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated;

notify pgrst, 'reload schema';
