create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  phone text,
  role text not null default 'customer',
  created_at timestamptz not null default now(),
  constraint profiles_role_check check (role in ('customer', 'admin'))
);

create table if not exists public.vendor_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  business_name text not null,
  phone text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vendor_requests_status_check
    check (status in ('pending', 'approved', 'rejected'))
);

alter table public.vendor_requests
  add column if not exists contact_name text,
  add column if not exists business_type text,
  add column if not exists registration_number text,
  add column if not exists tax_number text,
  add column if not exists website_url text,
  add column if not exists social_media_url text,
  add column if not exists street_address text,
  add column if not exists city text,
  add column if not exists province text,
  add column if not exists postal_code text,
  add column if not exists business_description text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'vendor_requests_business_type_check'
      and conrelid = 'public.vendor_requests'::regclass
  ) then
    alter table public.vendor_requests
      add constraint vendor_requests_business_type_check
      check (
        business_type is null or
        business_type in ('salon', 'stylist', 'retailer', 'wholesaler', 'online-store', 'other')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'vendor_requests_business_details_length_check'
      and conrelid = 'public.vendor_requests'::regclass
  ) then
    alter table public.vendor_requests
      add constraint vendor_requests_business_details_length_check
      check (
        char_length(contact_name) <= 120 and
        char_length(business_type) <= 50 and
        char_length(registration_number) <= 100 and
        char_length(tax_number) <= 100 and
        char_length(website_url) <= 500 and
        char_length(social_media_url) <= 500 and
        char_length(street_address) <= 200 and
        char_length(city) <= 100 and
        char_length(province) <= 100 and
        char_length(postal_code) <= 20 and
        char_length(business_description) <= 2000
      );
  end if;
end $$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  insert into public.profiles (id, first_name, last_name, phone)
  values (
    new.id,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name',
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (id) do nothing;
  return new;
end;
$function$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.vendor_requests enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
on public.profiles for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "Users can read their own vendor request" on public.vendor_requests;
create policy "Users can read their own vendor request"
on public.vendor_requests for select to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.profiles, public.vendor_requests from anon, authenticated;
grant select, update on table public.profiles to authenticated;
grant select on table public.vendor_requests to authenticated;
grant select, insert, update, delete on table public.profiles, public.vendor_requests to service_role;
grant usage, select on sequence public.vendor_requests_id_seq to service_role;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

notify pgrst, 'reload schema';
