create table if not exists public.vendor_products (
  id bigint generated by default as identity primary key,
  vendor_user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  collection text not null default 'everyday',
  hair_type text not null default 'Hair',
  product_type text not null default 'Vendor Product',
  price numeric(12,2) not null,
  old_price numeric(12,2),
  tag text,
  short_description text,
  description text,
  image_url text,
  sizes text[] not null default '{}',
  hair_origins text[] not null default '{}',
  details jsonb not null default '{}'::jsonb,
  stock_quantity integer not null default 0,
  status text not null default 'draft',
  rating numeric(2,1) not null default 0,
  review_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vendor_products_price_check check (price >= 0 and (old_price is null or old_price >= 0)),
  constraint vendor_products_stock_check check (stock_quantity >= 0),
  constraint vendor_products_status_check check (status in ('draft', 'active')),
  constraint vendor_products_rating_check check (rating >= 0 and rating <= 5),
  constraint vendor_products_details_check check (jsonb_typeof(details) = 'object')
);

create table if not exists public.store_orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_user_id uuid references auth.users(id) on delete set null,
  email text not null,
  phone text not null,
  delivery_address text not null,
  delivery_method text not null,
  payment_method text not null,
  items jsonb not null,
  subtotal numeric(12,2) not null,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null,
  status text not null default 'Order received',
  created_at timestamptz not null default now(),
  constraint store_orders_amounts_check check (subtotal >= 0 and delivery_fee >= 0 and total >= 0),
  constraint store_orders_items_check check (jsonb_typeof(items) = 'array'),
  constraint store_orders_status_check check (
    status in ('Order received', 'Processing', 'Dispatched', 'Delivered', 'Cancelled')
  )
);

create table if not exists public.vendor_orders (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.store_orders(id) on delete cascade,
  vendor_user_id uuid not null references auth.users(id) on delete restrict,
  order_number text not null,
  customer_email text not null,
  customer_phone text not null,
  delivery_address text not null,
  delivery_method text not null,
  items jsonb not null,
  subtotal numeric(12,2) not null,
  status text not null default 'Order received',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vendor_orders_items_check check (jsonb_typeof(items) = 'array'),
  constraint vendor_orders_subtotal_check check (subtotal >= 0),
  constraint vendor_orders_status_check check (
    status in ('Order received', 'Processing', 'Ready for dispatch', 'Dispatched', 'Completed', 'Cancelled')
  ),
  constraint vendor_orders_order_vendor_unique unique (order_id, vendor_user_id)
);

create index if not exists vendor_products_vendor_user_id_idx
  on public.vendor_products(vendor_user_id);
create index if not exists vendor_products_active_idx
  on public.vendor_products(id) where status = 'active';
create index if not exists store_orders_customer_created_idx
  on public.store_orders(customer_user_id, created_at desc);
create index if not exists vendor_orders_vendor_created_idx
  on public.vendor_orders(vendor_user_id, created_at desc);
create index if not exists vendor_orders_order_id_idx
  on public.vendor_orders(order_id);

alter table public.vendor_products enable row level security;
alter table public.store_orders enable row level security;
alter table public.vendor_orders enable row level security;

drop policy if exists "Approved vendors can read own products" on public.vendor_products;
create policy "Approved vendors can read own products"
on public.vendor_products for select to authenticated
using (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
);

drop policy if exists "Approved vendors can create own products" on public.vendor_products;
create policy "Approved vendors can create own products"
on public.vendor_products for insert to authenticated
with check (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
);

drop policy if exists "Approved vendors can update own products" on public.vendor_products;
create policy "Approved vendors can update own products"
on public.vendor_products for update to authenticated
using (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
)
with check (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
);

drop policy if exists "Approved vendors can delete own products" on public.vendor_products;
create policy "Approved vendors can delete own products"
on public.vendor_products for delete to authenticated
using (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
);

drop policy if exists "Customers can read own store orders" on public.store_orders;
create policy "Customers can read own store orders"
on public.store_orders for select to authenticated
using (customer_user_id = (select auth.uid()));

drop policy if exists "Approved vendors can read own orders" on public.vendor_orders;
create policy "Approved vendors can read own orders"
on public.vendor_orders for select to authenticated
using (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
);

drop policy if exists "Approved vendors can update own order status" on public.vendor_orders;
create policy "Approved vendors can update own order status"
on public.vendor_orders for update to authenticated
using (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
)
with check (
  vendor_user_id = (select auth.uid())
  and exists (
    select 1 from public.vendor_requests vr
    where vr.user_id = (select auth.uid()) and vr.status = 'approved'
  )
);

revoke all on public.vendor_products, public.store_orders, public.vendor_orders from anon, authenticated;
grant select, insert, update, delete on public.vendor_products to service_role;
grant select, insert, update, delete on public.store_orders to service_role;
grant select, insert, update, delete on public.vendor_orders to service_role;
grant usage, select on sequence public.vendor_products_id_seq to service_role;
grant usage, select on sequence public.store_orders_id_seq to service_role;
grant usage, select on sequence public.vendor_orders_id_seq to service_role;

notify pgrst, 'reload schema';
